name: Deploy siaguide.tech

on:
  # Trigger on pushes or PRs to any branch affecting any file
  push:
    branches:
      - '**'
    paths:
      - '**'
  pull_request:
    branches:
      - '**'
    paths:
      - '**'
  # Allow manual triggering
  workflow_dispatch:

# Prevent concurrent runs for the same branch/ref
concurrency: ${{ github.workflow }}-${{ github.ref }}

# Define necessary permissions for the workflow
permissions:
  pull-requests: write   # Required for potential PR comments (e.g., deployment links)
  deployments: write   # Required for creating deployments via wrangler-action
  contents: read      # Required for checking out the code

jobs:
  deploy:
    name: Build and Deploy siaguide.tech
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0 # Pinning Node.js version
          cache: 'npm'        # Enable caching for npm dependencies

      - name: Install dependencies
        run: npm ci # Use 'ci' for clean installs based on package-lock.json

      - name: Build project
        run: npm run build # Standard command to run the build script from package.json

      - name: Publish to Cloudflare Pages
        # Only publish on pushes to the main branch (adjust 'main' if needed)
        # You might want to add conditions here, e.g., if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Add other wrangler options if needed, e.g.:
          # accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # projectName: "your-project-name" # Often inferred, but can be explicit
          # directory: "./dist" # Or wherever your build output is